server:
  port: 8091
  group: gitgle

spring:
  application:
    name: domain-service
  datasource:
    url: jdbc:mysql://bj-cynosdbmysql-grp-pro0nh5i.sql.tencentcdb.com:25363/gitgle
    username: gitgle
    password: gitgle_1024
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        enabled: false
  redis:
    host: 49.232.232.203
    password: gitgle_1024
    port: 6379

dubbo:
  provider:
    group: ${server.group}
  consumer:
    group: ${server.group}
    timeout: 30000
  registry:
    address: nacos://121.36.79.38:8848
    group: ${server.group}
  protocol:
    name: dubbo
    port: 50090
  application:
    name: ${spring.application.name}
    logger: slf4j
    qos-port: 3333

kafka:
  bootstrap-servers: ckafka-9jnjx2m9.ap-beijing.ckafka.tencentcloudmq.com:50002
  sasl-jaas-config: /etc/ckafka_client_jaas.conf

xxl:
  job:
    admin:
      addresses: http://49.232.232.203:2222/xxl-job-admin
    accessToken: dasj2nd81jf9asjdkl5jk234
    executor:
      logretentiondays: 7
      port: 9091
      ip: 49.232.232.203
      logpath: ./log
      appname: ${spring.application.name}
