server:
  port: 8082
  group: gitgle

spring:
  application:
    name: talentrank-service
  datasource:
    url: jdbc:mysql://gitgle.mysql.polardb.rds.aliyuncs.com:3306/gitgle
    username: gitgle
    password: gitgle_1024
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        enabled: false

dubbo:
  provider:
    group: ${server.group}
  consumer:
    group: ${server.group}
    timeout: 60000
    check: false
  registry:
    address: nacos://121.36.79.38:8848
    group: ${server.group}
  protocol:
    name: dubbo
    port: 50070
  application:
    name: ${spring.application.name}
    logger: slf4j
    qos-port: 4444

kafka:
  bootstrap-servers: ckafka-9jnjx2m9.ap-beijing.ckafka.tencentcloudmq.com:50002
  sasl-jaas-config: /etc/ckafka_client_jaas.conf


