server:
  port: 8010
  group: gitgle

spring:
  application:
    name: nation-service
  datasource:
    url: jdbc:mysql://gz-cynosdbmysql-grp-f1gb8yz9.sql.tencentcdb.com:20381/gitgle
    username: root
    password: Gitgle_1024
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        enabled: false

dubbo:
  provider:
    group: ${server.group}
  consumer:
    group: ${server.group}
    timeout: 60000
    check: false
  registry:
    address: nacos://121.36.79.38:8848
    group: ${server.group}
  protocol:
    name: dubbo
    port: 50100
  application:
    name: ${spring.application.name}
    logger: slf4j

kafka:
  bootstrap-servers: ckafka-9jnjx2m9.ap-beijing.ckafka.tencentcloudmq.com:50002
  sasl-jaas-config: /etc/ckafka_client_jaas.conf
