server:
  port: 8081
  group: gitgle

spring:
  application:
    name: data-service
  datasource:
    url: jdbc:mysql://gitgle.mysql.polardb.rds.aliyuncs.com:3306/gitgle
    username: gitgle
    password: gitgle_1024
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        enabled: false
  redis:
    host: 49.232.232.203
    password: gitgle_1024
    port: 6379

github:
  auth-token:
    list:

dubbo:
  provider:
    group: ${server.group}
  consumer:
    group: ${server.group}
  registry:
    address: nacos://121.36.79.38:8848
    group: ${server.group}
  protocol:
    name: dubbo
    port: 50060
  application:
    name: ${spring.application.name}
    logger: slf4j
    qos-accept-foreign-ip: true

kafka:
  bootstrap-servers: ckafka-9jnjx2m9.ap-beijing.ckafka.tencentcloudmq.com:50002
  sasl-jaas-config: /etc/ckafka_client_jaas.conf

xxl:
  job:
    admin:
      addresses: http://49.232.232.203:2222/xxl-job-admin
    accessToken: dasj2nd81jf9asjdkl5jk234
    executor:
      logretentiondays: 7
      port: 9081
      ip: 49.232.232.203
      logpath: ./log
      appname: ${spring.application.name}