server:
  port: 8081

spring:
  application:
    name: data-service
  datasource:
    url: jdbc:mysql://gitgle.mysql.polardb.rds.aliyuncs.com:3306/gitgle
    username: gitgle
    password: gitgle_1024
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 121.36.79.38:8848
  redis:
    host: 49.232.232.203
    password: gitgle_1024
    port: 6379

github:
  auth-token:
    list:
#      - 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
      - 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
#      - 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

dubbo:
  registry:
    address: nacos://121.36.79.38:8848
  protocol:
    name: dubbo
    port: 50060
  application:
    name: ${spring.application.name}
    logger: slf4j

kafka:
  bootstrap-servers: ckafka-9jnjx2m9.ap-beijing.ckafka.tencentcloudmq.com:50002
  sasl-jaas-config: /etc/ckafka_client_jaas.conf

xxl:
  job:
    admin:
      addresses: http://49.232.232.203:2222/xxl-job-admin
    accessToken: dasj2nd81jf9asjdkl5jk234
    executor:
      logretentiondays: 7
      port: 9081
      logpath: ./
      appname: ${spring.application.name}