
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://bj-cynosdbmysql-grp-pro0nh5i.sql.tencentcdb.com:25363/gitgle?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: gitgle
    password: gitgle_1024
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        register-enabled: true
        server-addr: 121.36.79.38:8848

  redis:
    host: 49.232.232.203
    password: gitgle_1024
    port: 6379

  mail:
    # 编码格式
    default-encoding: UTF-8
    host: smtp.126.com
    username: gitgle@126.com #自己的邮箱
    password: NJ3zAsQWnBagKLdp #授权码，并不是qq密码
    properties:
      mail:
        smtp:
          ssl:
            enable: true


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.gitgle.mapper

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

dubbo:
  registry:
    address: nacos://121.36.79.38:8848
    register-mode: all
  protocol:
    name: dubbo
    port: -1
  application:
    name: ${spring.application.name}
    logger: slf4j
    serialize-check-status: DISABLE

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Access-Token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token风格
  token-style: random-32
  # 是否尝试从 header 里读取 Token
  is-read-header: true
  # 是否开启自动续签
  auto-renew: true
  # 临时有效期，单位s，例如将其配置为 1800 (30分钟)，代表用户如果30分钟无操作，则此Token会立即过期
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时同端互斥)
  is-concurrent: true
  # 配置 Sa-Token 单独使用的 Redis 连接
  alone-redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 49.232.232.203
    # Redis服务器连接端口
    port: 6379
    password: gitgle_1024
    # 连接超时时间
    timeout: 10s

kafka:
  bootstrap-servers: ckafka-9jnjx2m9.ap-beijing.ckafka.tencentcloudmq.com:50002
  sasl-jaas-config: /etc/ckafka_client_jaas.conf
server:
  port: 8080
