spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://121.36.79.38:3306/gitgle?useSSL=false&serverTimezone=UTC
    username: root
    password: gitgle_1024
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 8.137.36.93
    password: gitgle_1024
    port: 6379

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package:

dubbo:
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
  protocol:
    name: dubbo
    port: 50061
  application:
    name: ${spring.application.name}
    logger: slf4j

