name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: 生成jar包
        run: mvn clean install
#        env:
#          JARS: >-
#            data-service.jar
#            talentrank-service.jar
#            nation-service.jar
#            user-service.jar
#            domain-service.jar
#            api-service.jar
#            gateway-service.jar

      - name: 确定修改的文件
        id: modified_files
        run: |
          echo "modified_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})" >> $GITHUB_ENV

      - name: 设置JAR环境变量
        run: |
          jars=""
          for file in ${{ env.modified_files }}; do
            dir_name=$(basename $(dirname "$file"))
            case $dir_name in
              data-service)
                jars+="data-service.jar "
                ;;
              talentrank-service)
                jars+="talentrank-service.jar "
                ;;
              nation-service)
                jars+="nation-service.jar "
                ;;
              user-service)
                jars+="user-service.jar "
                ;;
              domain-service)
                jars+="domain-service.jar "
                ;;
              api-service)
                jars+="api-service.jar "
                ;;
              gateway-service)
                jars+="gateway-service.jar "
                ;;
            esac
          done
          echo "JARS=$jars" >> $GITHUB_ENV

      - name: 停止之前运行的jar包
        if: always()
        uses: fifsky/ssh-action@master
        with:
          command: |
            # 进入gitgle目录
            cd gitgle || exit
            # 停止所有匹配的Java进程
            for jar in $(ls *.jar); do
              pkill -f "$jar"
            done
          host: ${{ secrets.HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          args: "-tt"

      - name: 上传Data服务
        if: contains(env.JARS, 'data-service.jar')
        uses: garygrossgarten/github-action-scp@release
        with:
          local: data-service/data-service-server/target/data-service.jar
          remote: gitgle/data-service.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: 上传talentRank服务
        if: contains(env.JARS, 'talentrank-service.jar')
        uses: garygrossgarten/github-action-scp@release
        with:
          local: talentrank-service/talentrank-service-server/target/talentrank-service.jar
          remote: gitgle/talentrank-service.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: 上传Nation服务
        if: contains(env.JARS, 'nation-service.jar')
        uses: garygrossgarten/github-action-scp@release
        with:
          local: nation-service/nation-service-server/target/nation-service.jar
          remote: gitgle/nation-service.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: 上传User服务
        if: contains(env.JARS, 'user-service.jar')
        uses: garygrossgarten/github-action-scp@release
        with:
          local: user-service/user-service-server/target/user-service.jar
          remote: gitgle/user-service.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: 上传Domain服务
        if: contains(env.JARS, 'domain-service.jar')
        uses: garygrossgarten/github-action-scp@release
        with:
          local: domain-service/domain-service-server/target/domain-service.jar
          remote: gitgle/domain-service.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: 上传Api服务
        if: contains(env.JARS, 'api-service.jar')
        uses: garygrossgarten/github-action-scp@release
        with:
          local: api-service/target/api-service.jar
          remote: gitgle/api-service.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: 上传Gateway服务
        if: contains(env.JARS, 'gateway-service.jar')
        uses: garygrossgarten/github-action-scp@release
        with:
          local: gateway-service/target/gateway-service.jar
          remote: gitgle/gateway-service.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: 按顺序运行jar包
        if: always()
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd gitgle
            java -jar data-service.jar
            sleep 6
            java -jar talentrank-service.jar
            sleep 6            
            java -jar nation-service.jar
            sleep 6 
            java -jar user-service.jar
            sleep 6
            java -jar domain-service.jar
            sleep 6
            java -jar api-service.jar
            sleep 6
            java -jar gateway-service.jar
          host: ${{ secrets.HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          args: "-tt"