name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: 生成jar包
        run: mvn clean install
        env:
          JARS: >-
            data-service.jar
            talentrank-service.jar
            nation-service.jar
            user-service.jar
            domain-service.jar
            api-service.jar
            gateway-service.jar

      - name: 停止之前运行的jar包
        if: always()
        uses: fifsky/ssh-action@master
        with:
          command: |
            # 停止所有匹配的Java进程
            for jar in ${{ env.JARS }}; do
              pkill -f "gitgle/$jar"
            done
          host: ${{ secrets.HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          args: "-tt"

      - name: 上传Data服务
        uses: garygrossgarten/github-action-scp@release
        with:
          local: data-service/data-service-server/target/data-service.jar
          remote: gitgle/data-service.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: 上传talentRank服务
        uses: garygrossgarten/github-action-scp@release
        with:
          local: talentrank-service/talentrank-service-server/target/talentrank-service.jar
          remote: gitgle/talentrank-service.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: 上传Nation服务
        uses: garygrossgarten/github-action-scp@release
        with:
          local: nation-service/nation-service-server/target/nation-service.jar
          remote: gitgle/nation-service.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: 上传User服务
        uses: garygrossgarten/github-action-scp@release
        with:
          local: user-service/user-service-server/target/user-service.jar
          remote: gitgle/user-service.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: 上传Domain服务
        uses: garygrossgarten/github-action-scp@release
        with:
          local: domain-service/domain-service-server/target/domain-service.jar
          remote: gitgle/domain-service.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: 上传Api服务
        uses: garygrossgarten/github-action-scp@release
        with:
          local: api-service/target/api-service.jar
          remote: gitgle/api-service.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: 上传Gateway服务
        uses: garygrossgarten/github-action-scp@release
        with:
          local: gateway-service/target/gateway-service.jar
          remote: gitgle/gateway-service.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: 按顺序运行jar包
        if: always()
        uses: fifsky/ssh-action@master
        with:
          command: |
            for jar in ${{ env.JARS }}; do
              java -jar "gitgle/$jar" &
              sleep 6
            done
          host: ${{ secrets.HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          args: "-tt"