spring:
  application:
    name: data-service
  datasource:
    url: jdbc:mysql://gitgle.mysql.polardb.rds.aliyuncs.com:3306/gitgle
    username: gitgle
    password: gitgle_1024
    driver-class-name: com.mysql.jdbc.Driver

dubbo:
  registry:
    address: nacos://121.36.79.38:8848
  protocol:
    name: dubbo
    port: 50060
  application:
    name: ${spring.application.name}
    logger: slf4j


