spring:
  application:
    name: data-service

  datasource:
    url: jdbc:mysql://121.36.79.38:3306/gitgle?useSSL=false&serverTimezone=UTC
    username: root
    password: gitgle_1024
    driver-class-name: com.mysql.cj.jdbc.Driver

dubbo:
  registry:
    address: nacos://121.36.79.38:8848
  protocol:
    name: dubbo
    port: 50060
  application:
    name: ${spring.application.name}
    logger: slf4j


